config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'
  devise_for :admins
  resources :organizations
  resources :animals
  get "/about", to:"organizations#about", as:"about"
  get "/faq", to:"organizations#faq", as:"faq"
  get "/contact" => 'organizations#about'
  post "/contact", to:"organizations#contact"
  post 'animals/:id/purchase' => 'animals#purchase', as: :purchase
  get 'animals/:id/purchase_succeeded' => 'animals#purchase_succeeded', as: :purchase_succeded
  get 'animals/:id/purchase_failed' => 'animals#purchase_failed', as: :purchase_failed

end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :organization
  has_many :donation_records
  has_attached_file :picture, styles: { medium: "300x300#", small: "200x200#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  is_impressionable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :purchase, :purchase_succeeded, :purchase_failed, :edit, :update, :destroy]
  before_action :check_logged_in, only: [:new, :edit, :destroy]

  impressionist 

  # GET /animals
  # GET /animals.json
  def index
    if (params[:species] == nil) 
        @animals = Animal.all
    else
	# use whereby since find_by_species only returns 1 record
	# also use the array version to prevent sql injection
        @animals = Animal.where("species = ?", params[:species])
    end
    @species = Animal.select("species").distinct
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
     set_organization
     if admin_signed_in? && (@animal.organization_id == current_admin.organization_id ||
			     current_admin.superUser == true)
         @display_edit_link = 1
     end 
  end

  # GET /animals/new
  def new
    @animal = Animal.new
    set_possible_organizations
  end

  # GET /animals/1/edit
  def edit
    if current_admin.superUser == false &&
       @animal.organization_id != nil && 
       @animal.organization_id != current_admin.organization_id
          flash[:error] = "You are not an admin for this animal's sanctuary"
          redirect_to edit_admin_registration_path
    end
    set_possible_organizations
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def purchase
    if params[:amount] == "0" || params[:amount] == ""
        @errors = "Please enter a dollar amount"
        redirect_to @animal
    end 

    init_paypal_api
    @pay = @api.build_pay({
  		:actionType => "PAY",
  		:currencyCode => "USD",
  		:feesPayer => "EACHRECEIVER",
		:memo => "Donation for " + @animal.name,
  		:returnUrl => purchase_succeded_url(@animal),
  		:cancelUrl => purchase_failed_url(@animal) })

	@pay.receiverList.receiver[0] = { :amount => params[:amount], 
					  :email => @animal.organization.paypalEmail }

	# Make API call & get response
	@response = @api.pay(@pay)

	# Access response
	if @response.success? && @response.payment_exec_status != "ERROR"
  		# logger.info(@response.payKey)
		session[:paypalPaykey] = @response.payKey
  		redirect_to @api.payment_url(@response)  # Url to complete payment
	else
		# logger.info("Fail")
  		@response.error[0].message
	end
  end 

  def purchase_succeeded
     set_organization
     init_paypal_api

     # Build request object
     @payment_details = @api.build_payment_details({
     :payKey => session[:paypalPaykey] })

     # Make API call & get response
     @payment_details_response = @api.payment_details(@payment_details)
     # logger.info(@payment_details_response.status)
     if (@payment_details_response.status == "COMPLETED")
	# if the user hits the "return to vendor page" button on paypal
	# multiple times, then this payment_succeeded gets called multiple times.
	# so we check to see if the donation has already been processed.
	donation_record = 
               @animal.donation_records.find_by(:paypalKey => session[:paypalPaykey])
	if (donation_record == nil)
	   @donation_amount = 
	       @payment_details_response.paymentInfoList.paymentInfo[0].receiver.amount
           donation=DonationRecord.new
           donation.paypalKey = session[:paypalPaykey]
           donation.amount = @payment_details_response.paymentInfoList.paymentInfo[0].receiver.amount
           donation.senderEmail = @payment_details_response.senderEmail
           donation.animal = @animal
           donation.save
	   @animal.amountRaised += donation.amount
	   @animal.save
           session.delete(:paypalPaykey)

	   # Send a confirmation email to the person who donated
	    DonorMailerJob.perform_async(@payment_details_response.senderEmail,
	   		                 @animal.name, 
	   	                         donation.amount.to_s(),
	   		                 @animal.organization.paypalEmail,
	   	                         @animal.organization.name)

	   # Send an email to the sanctuary about the donation
	   SanctuaryMailerJob.perform_async(@payment_details_response.senderEmail,
		  			    @animal.name, @animal.species,
		  			    donation.amount.to_s(),
		  			    @animal.organization.paypalEmail)
        else
	   @donation_amount = donation_record.amount
           # logger.info("****** RECORD EXISTs ********")
        end
     else 
	session.delete(:paypalPaykey)
	redirect_to purchase_failed_url(@animal)
     end
  end

  def purchase_failed
      # @amount = session[:animal_donation_amount]
      set_organization
      @donation_message = "Your donation payment was either cancelled or unsuccessful."
      render "show"
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    def set_organization
      @organization = Organization.find(@animal.organization_id);
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:name, :species, :summary, :fullDescription, :amount, :amountRaised, :picture, :organization_id, :monthly_sponsorship)
    end

    def set_possible_organizations
       if current_admin.superUser == true
           @organizations = Organization.all
       else
           @organizations = (Array.new).push(Organization.find(current_admin.organization_id))
           @animal.organization_id = current_admin.organization_id
       end
    end 

    def check_logged_in
        unless admin_signed_in?
           flash[:error] = "You need to be logged in to add or edit an animal"
	   redirect_to new_admin_session_path
	end
    end

    def init_paypal_api
        require 'paypal-sdk-adaptivepayments'
        @api = PayPal::SDK::AdaptivePayments.new
     end

end	

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.erb
<%= form_for @animal, html: { multipart: true}  do |f| %>
  <% if @animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% @animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :species %><br>
    <%= f.text_field :species, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :fullDescription %><br>
    <%= f.text_area :fullDescription, class:"form-control" %>
  </div>
  <div class="form-horizontal field">
    <%= f.check_box :monthly_sponsorship %>
    <%= f.label "Monthly Sponsorship" %><br>
  </div>
  <div class="form-group field">
  <%= f.label :organizationName %>
  <div class="form-control"><%= collection_select(:animal, :organization_id, @organizations, :id, :organizationName, prompt: true) %></div>
  </div>
  <div class="form-group field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :amountRaised %><br>
    <%= f.text_field :amountRaised, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>
  <div class="form-group actions">
    <%= f.submit "Submit"%>
  </div>
<% end %>
<br>

app/views/animals/edit.html.erb
<div class="container row">
<div class="col-lg-offset-3 col-md-offset-3 col-lg-9 col-md-6 col-xs-12">
<h1>Editing Animal</h1>

<%= render 'form' %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>
</div>
</div>

app/views/animals/index.html.erb
<!-- Google Code for Home Page Visit Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 873737126;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "ON2uCPK8nG4QptfQoAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/873737126/?label=ON2uCPK8nG4QptfQoAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<!-- START OF ANIMALWISHES HTML -->
<div class="container">

<div class="row text-al-center" id="topBanner">
<div id="topLine"><h3>Donate to Sanctuaries that have rescued farm & domestic Animals</h3></div>
<div id="bottomLine"><h4>100% of your support goes towards the Animals</h4></div>
</div>
 <div class="row">
   <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="12000">
     <!-- Indicators -->
       <ol class="carousel-indicators">
         <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
         <li data-target="#carousel-example-generic" data-slide-to="1"></li>
         <li data-target="#carousel-example-generic" data-slide-to="2"></li>
       </ol>

     <!-- Wrapper for slides -->
       <div class="carousel-inner" role="listbox">
	  <% carousel_caption = "<h2>Discover the stories and unique personalities of rescued Animals and Support them</h2>
        <p><b>100% of your donation goes to the Animals and their Sanctuaries</b></p>" %>
          <div class="item active">
               <image src="https://s3.amazonaws.com/sagarwal10-animals/static/cow.jpg" >
               <div class="carousel-caption">
               <%= carousel_caption.html_safe %>
               </div>
           </div>
           <div class="item">
               <image src="https://s3.amazonaws.com/sagarwal10-animals/static/duck.jpg" >
               <div class="carousel-caption">
               <%= carousel_caption.html_safe %>
               </div>
           </div>
           <div class="item">
               <image src="https://s3.amazonaws.com/sagarwal10-animals/static/rabbits.jpg" >
               <div class="carousel-caption">
               <%= carousel_caption.html_safe %>
               </div>
           </div>
        </div>

     <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
        </a>
    </div>
    <div  class="main-text ">
    </div>
  </div>

  <div class="row"> 
  <div id="categoryselect" class="hidden-lg hidden-md col-sm-3 col-sm-offset-9 col-xs-4 col-xs-offset-8">
      <button id="animalselectdropdown" class="btn btn-default dropdown-toggle " type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Filter Animals
          <span class="caret"></span>
      </button>
      <ul class="dropdown-menu "  aria-labelledby="dropdownMenu1"> 
         <li class="pl1">
	    <input type="checkbox" id="clearall-dropdown" name="animal" value="Clear All" /><b>Clear All</b>
         </li>
         <% @species.each do |s| %>
         <li class="pl1">
             <input type="checkbox" id="animalselector-dropdown-<%= s.species %>" class="animalselector" checked name="animal" value="<%= s.species %>" /><%= s.species %>
         </li>
         <% end %>
      </ul>
   </div>
  </div>

 <div class="row" id="donation_section">
 <h3 class="text-center"><b>Meet the Animals</b></h3>
<div id="donateInstructions"><h5 class="text-center">(click on the picture of an Animal to read more about them & donate)</h5></div>
<br>
 </div>
 <div class="row">
    <div id="animallist-sidebar" class="hidden-xs hidden-sm col-lg-2 col-md-2">
       <br>
       <h4>See...</h4>
       <hr>
       <% @species.each do |s| %>
           <input type="checkbox" class="animalselector" id="animalselector-sidebar-<%= s.species %>" checked name="animal" value="<%= s.species %>" /><%= s.species %><br>
       <% end %>
       <input type="checkbox" id="clearall" name="animal" value="Clear All" /><b>Clear All</b><br>
    </div>
    <div id="animallist" class="col-lg-10 col-md-10">
        <div class="row">
        <% @animals.each do |animal| %>
        <div class="animal-<%= animal.species %> col-lg-3 col-md-4 col-sm-6 col-xs-8 col-xs-offset-3 col-lg-offset-0 col-md-offset-0 col-sm-offset-0 ">
           <div class="animalindex glassy-bg radius-box m1 ell">
             <%= link_to animal_path(animal) do %>
             <%= image_tag animal.picture.url(:small), class: "radius-box mtm" %>
             <% end %>
             <div id="animalcaption" class="caption">
                 <div id="animalname"><strong><%= animal.name %></strong></div>
                 <div id="animalneed" class="pr1 pl1 pb1 pt1">
		    <i>
			<% if animal.monthly_sponsorship %>
			    Monthly Care
			<% else %>
			    <%= animal.summary %>
			<% end %>
		    </i>
		 </div>
                 <div id="animaldescription" class="pr1 pl1"><%= truncate(animal.fullDescription, length:140) %></div>
             </div>
           </div>
        </div>
        <% end %>
    </div>
    </div>
 </div>
<div>

app/views/animals/new.html.erb
<div class="container row">
<div class="col-lg-offset-3 col-md-offset-3 col-lg-9 col-md-6 col-xs-12"> 
<h1>New Animal</h1>

<%= render 'form' %>

<%= link_to 'Back', animals_path %>
</div>
</div>

app/views/animals/purchase.html.erb
<h1>Purchasing</h1>
<%= @response.inspect %>

app/views/animals/purchase_failed.html.erb
Purchase failed
<%= @animal.name %>
<%= @amount %>

app/views/animals/purchase_succeeded.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
<div class="text-al-center"><h2>Thank You!</h2></div>
<br>
<br>
Your donation of $<%= @donation_amount %> to <%= @animal.name %> is deeply appreciated.
<br>
An email will be sent to you with details of your donation.
<br>
<br>
<div class="text-al-center">
   <%= link_to 'Browse More Animals', animals_path %>
</div>
<br> 
<%= image_tag @animal.picture.url, class: "radius-box mtm fit" %>
<br>
<br>
<%= render 'organizations/logo' %>
<br>
<br>
<br>
<br>
</div>
</div>

app/views/animals/show.html.erb
<!-- Google Code for Animal Click Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 873737126;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "EagmCOHGjG4QptfQoAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/873737126/?label=EagmCOHGjG4QptfQoAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<!-- Google Code for Donation Button Click Conversion Page
In your html page, add the snippet and call
goog_report_conversion when someone clicks on the
chosen link or button. -->
<script type="text/javascript">
  /* <![CDATA[ */
  goog_snippet_vars = function() {
    var w = window;
    w.google_conversion_id = 873737126;
    w.google_conversion_label = "Vf5KCM6aoW4QptfQoAM";
    w.google_conversion_value = 1.00;
    w.google_conversion_currency = "USD";
    w.google_remarketing_only = false;
  }
  // DO NOT CHANGE THE CODE BELOW.
  goog_report_conversion = function(url) {
    goog_snippet_vars();
    window.google_conversion_format = "3";
    var opt = new Object();
    opt.onload_callback = function() {
    if (typeof(url) != 'undefined') {
      window.location = url;
    }
  }
  var conv_handler = window['google_trackConversion'];
  if (typeof(conv_handler) == 'function') {
    conv_handler(opt);
  }
}
/* ]]> */
</script>
<script type="text/javascript"
  src="//www.googleadservices.com/pagead/conversion_async.js">
</script>


<!-- HTML FOR ANIMALWISHES --> 
   <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav" role="tablist">
   <% if @display_edit_link == 1 %>
    <li role="presentation" class="sidebar-brand"><%= link_to 'Edit Entry', edit_animal_path(@animal) %></li>
   <% end %>
    <li role="presentation" class="sidebar-brand"><a href="#profile" aria-controls="profile" role="tab" data-toggle="profile"><%= "About #{@animal.name}" %></a></li>
    <li role="presentation" class="sidebar-brand"><a href="#donate" aria-controls="messages" role="tab" data-toggle="donate">Donate</a></li>
    <li role="presentation" class="sidebar-brand"><a href="#organization" aria-controls="settings" role="tab" data-toggle="organization"><%= "About #{@animal.name}'s Home" %></a></li>
    <li role="presentation" class="sidebar-brand"><%= link_to 'Back to the Animals', root_url %></li>
  </ul>
</div>


<div id="page-content-wrapper">
<div class="container-fluid">

<% if @donation_message != nil %>
<div class="row text-al-center">
<div class="alert alert-danger alert-dismissible" role="alert">
<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h4><%= @donation_message %></h4>
</div>
</div>
<% end %> 

<div class="row">
<div class="col-sm-offset-1 col-sm-9">
<div id="animalname"><h1><%= @animal.name %></h1></div>
<%= image_tag @animal.picture.url, class: "radius-box mtm animalfullpicture" %>
<a name="profile"></a>  
<div id="animalfulldescription" class=""><%= simple_format(@animal.fullDescription) %></div>
<a name="donate"></a>
<h2 class="text-al-center"><u>Donate</u></h2>
<div id="animalneedshowpage" >
<h3>
<br>
<% if @animal.monthly_sponsorship %>
    <i><%= "Contribute to #{@animal.name}'s monthly food & living" %></i>
    <br>
<% else %>
    <i><%= @animal.summary %></i>
<% end %>
</h3>
</div>
<br>
<div class="text-right" >Total requested: $<%= number_with_precision(@animal.amount, precision: 2) %>. Still needed: <b>$<%= number_with_precision(@animal.amount - @animal.amountRaised, precision: 2) %></b></div>
<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:<%= @animal.amountRaised*100/@animal.amount %>%;" >
    <%= (@animal.amountRaised*100/@animal.amount).floor %>%
  </div>
</div>
<%= form_tag(purchase_url(@animal.id), method: "post", id:"donateForm") do %>
<%= number_field(nil, :amount, class:"donateField", 
		 in: 1..(@animal.amount - @animal.amountRaised), 
	 	 step: 0.01,
		 placeholder:"Enter a donation amount from $0.50 to " +
			     number_with_precision(@animal.amount-@animal.amountRaised, precision: 2) ) %>
<button type="submit" onclick="goog_report_conversion(nil)"  class="pull-right donateButton btn btn-primary ">Donate
</button>
<div id="animalamountmessage" class="text-left">(any contribution amount upto the total needed is appreciated)</div>
<div id="animalamountmessage"><%= "(Note: This is a one time only contribution)" %></div>
<a class="pull-right"  href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;"><img style="width:80%" class="pull-right" src="https://www.paypalobjects.com/digitalassets/c/website/marketing/na/us/logo-center/9_bdg_secured_by_pp_2line.png" border="0" alt="Secured by PayPal"></a>

<% end %>
<br>
<br><br><br>
<br><br><br>

<a name="organization"></a>
<h2 class="text-al-center" ><u><%= "#{@animal.name}'s Home" %></u></h2>
<br>
<%= render 'organizations/show' %>
     </div>
   </div>
  </div>
  <!-- /#page-content-wrapper -->
 </div>
</div>