config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'
  devise_for :admins
  resources :organizations
  resources :animals
  get "/about", to:"organizations#about", as:"about"
  get "/faq", to:"organizations#faq", as:"faq"
  get "/contact" => 'organizations#about'
  post "/contact", to:"organizations#contact"
  post 'animals/:id/purchase' => 'animals#purchase', as: :purchase
  get 'animals/:id/purchase_succeeded' => 'animals#purchase_succeeded', as: :purchase_succeded
  get 'animals/:id/purchase_failed' => 'animals#purchase_failed', as: :purchase_failed

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :animals, dependent: :destroy
  has_many :admins, dependent: :destroy
  has_attached_file :logo, styles: { small: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
  def organizationName
     "#{name}"
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_action :check_superuser_privelege, only: [:new, :edit, :destroy] 

  impressionist

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def contact	
	if (verify_recaptcha == false)
	    @captcha_error = "You failed to verify that you're not a robot - please check the Captcha field in the form below and resubmit"
	    @email_content = params[:email]
	    @name_content = params[:name]
	    @message_content = params[:message]
	    render 'about' and return
	end

        ContactMailerJob.perform_async(
		ERB::Util.html_escape(params[:email]),
	        ERB::Util.html_escape(params[:name]),
		ERB::Util.html_escape(params[:message]))
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    # @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @signed_in = admin_signed_in?
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :about, :url, :logo, :paypalEmail, :contactEmail)
    end

    def check_superuser_privelege
      if admin_signed_in?
        if current_admin.superUser == false
           flash[:error] = "You need superuser priveleges for that"
           redirect_to edit_admin_registration_path
	end
      else 
        redirect_to new_admin_session_path
      end
    end 


end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for @organization, html: {multipart:true} do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label "Paypal Email" %><br>
    <%= f.email_field :paypalEmail, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label "Contact Email (if different than Paypal)" %><br>
    <%= f.email_field :contactEmail, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :about %><br>
    <%= f.text_area :about, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class:"form-control" %>
  </div>
  <div class="form-group field">
    <%= f.label :logo %><br>
    <%= f.file_field :logo %>
  </div>
  <div class="form-group actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/_logo.html.erb
<div class="center-block"><%= image_tag @organization.logo.url, class:"center-block" %></div>

app/views/organizations/_show.html.erb
<div class="center-block"><%= image_tag @organization.logo.url, class:"center-block" %></div>

<div id="animalorg" class="pb1">
<%= link_to "#{@organization.name}", @organization.url, class:"animalorg" %> 
</div>

<br>
<p class="center-block">
  <%= @organization.about %>
</p>

app/views/organizations/about.html.erb
<!-- Google Code for About Page Visit Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 873737126;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "0hJPCOS9pm4QptfQoAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/873737126/?label=0hJPCOS9pm4QptfQoAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<!-- START OF ANIMALWISHES HTML -->
<div class="container">

<% if @captcha_error != nil %>
    <div class="row text-al-center alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= @captcha_error %>
    </div>
<% else %>
   <div class="row text-al-center" id="topBanner">
   <div id="topLine">About AnimalWishes</div>
   </div>
<% end %>

<div class="row"> 
<div class="col-md-2 ">
<image class="aboutImg" src="https://s3.amazonaws.com/sagarwal10-animals/static/Self.jpg" >
</div>
<div class="col-md-8">
<b>How can we help the voiceless animals who are in need but
can't speak for themselves?</b>
<br><br>
Thanks for visiting this website. <br><br>
My name is Shalabh. I live
in the beautiful San Francisco Bay area region.
<br><br>
As an Animal lover, I wanted to build something that 
would help Animals in need. <br><br>
After having visited a couple
of Animal sanctuaries in the Bay area, I realized something. 
<br>
<br>
A lot of the sanctuaries are doing amazing work fostering and caring for
animals that have been rescued after being abandoned as pets or having escaped from factory farms and other
horrible conditions. <br><br>
However, these sanctuaries each have their own separate web presence
and the thought occurred to me that perhaps there could be one
platform to showcase all the work being done by them. And while we're at it, why not also have 
one common place for people to donate to the sanctuaries and animals. 
<br>
<br>
Animal Wishes is the result of this effort. I hope it will help you connect with 
and donate to Animals in need. I also hope you go visit them. 
<br>
<br>
100% of your donations go to the sanctuary and the Animals. 
<br><br>
</div>
<div class="col-md-6 col-md-offset-3">
<a href="#contact"><div id="contact" class="text-al-center"><u>Contact</u></div></a>
<br>
<br>
<%= form_tag(contact_url) do %>
  <div class="form-group">
    <label>Name</label>
    <%= text_field_tag 'name', @name_content, class:"form-control",
    placeholder:"Enter Your name"  %>
  </div>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <%= email_field_tag 'email', @email_content, class:"form-control",
    placeholder:'Enter your email address', :required => true %>
  </div>
  <div class="form-group">
    <label>Message</label>
    <%= text_area_tag 'message', @message_content, rows:4, class:"form-control",
        placeholder: "Enter your message", :required => true %>
  </div>
  <%= recaptcha_tags :ssl => true %>
  <br>
<button type="submit" class="btn btn-default btn-sm">Submit</button>
<% end %>
<br><br><br>
</div>
</div>
</div>

app/views/organizations/contact.html.erb
<div class="row">
<div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3">
<div class="text-al-center"><h2>Thank You for contacting us!</h2></div>
<div class="text-al-center"><h3>We will get back to you shortly!</h3></div>
<br>
<br>
<div class="text-al-center">
   <%= link_to 'Browse More Animals', animals_path %>
</div>
<br> 
<br>
</div>
</div>

app/views/organizations/edit.html.erb
<div class="container row">
<div class="col-lg-offset-3 col-md-offset-3 col-lg-9 col-md-6 col-xs-12">
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>
</div>
</div>

app/views/organizations/faq.html.erb
<!-- Google Code for How This Works Visit Conversion Page -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 873737126;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "SwysCJC6pm4QptfQoAM";
var google_remarketing_only = false;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/873737126/?label=SwysCJC6pm4QptfQoAM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>

<!-- Start of Animal Wishes HTML -->
<div class="container">

<% if @captcha_error != nil %>
    <div class="row text-al-center alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= @captcha_error %>
    </div>
<% else %>
   <div class="row text-al-center" id="topBanner">
   <div id="topLine">How this website works & frequently asked questions</div>
   </div>
<% end %>

<div class="row"> 
<div class="col-md-4 ">
<%= image_tag("gorilla.jpg", class:"aboutImg") %>
</div>
<div class="col-md-8">
The hope behind this website is for us to better identify with animals as fellow sentient beings - beings with personalities, character, stories, emotions, struggles, needs, hopes & desires. 
<br>
<br> 
<b>What are Animal Sanctuaries?</b><br>
Animals face a lot of struggle in this World. They are enslaved in meat, egg & dairy factory farms. <br>
Or if they were raised as pets, they can be abused and often abandoned. <br>
Millions of them perish. A lucky few escape or get rescued. But where do these animals go?<br><br>
A handful of amazing individuals have committed themselves to taking care of these animals and letting them live out the rest of their lives in a peaceful and loving environment.<br><br>
These sanctuaries are set up on farms where the animals have the freedom to live in a more natural environment.
<br><br>
<b>How do you select the animals & sanctuaries featured on the website?</b><br>
We contact established sanctuaries around the World and invite them to be a part of the website. They then tell us which of their residents they want featured on the site. <br><br>
Often they have their own website where you can donate directly. We encourage that and invite you to establish a relationship with them directly.
The philosophy behind Animal Wishes is to just be a discovery portal to the various animals & sanctuaries.
<br><br>
<b>What is the money used for? How is the transaction handled?</b><br>
The money is used by the sanctuaries for either monthly sponsorship of animals (for their food and feed) or sometimes for special projects (e.g. building fences or enclosures for the animals).<br><br>
When you choose to donate to an animal, you are taken to a <b>PayPal</b> page where you log into your account and send money <b>directly</b> to the sanctuary. Paypal fees are paid by the sanctuary.<br><br>
We do NOT receive or participate in the money exchange.  
<br><br>
<b>How is this website funded?</b><br>
All of the money you donate goes directly to the sanctuary. Even though we facilitate the donation between you and the sanctuary, we do NOT participate in the money exchange. We do NOT collect any money, fees or commissions from anyone.<br><br>
The hosting costs for this site are borne by us. We might add advertizing in the future or explicitly ask for donations to help offset these expenses.
<br><br>
<b>How do I get a tax donation receipt? How do I get updates on the animals?</b><br>
Unfortunately, there is no standard procedure in place currently. <br><br>
Right now your best bet is to email the sanctuary directly (if you choose to donate, you will receive an email with their contact information).
<br><br>
<br><br>
If you have any other questions, please <%= link_to "contact us", about_path(anchor:"contact") %>. Thank you for your support.

</div>
</div>
</div>
<br><br><br><br><br>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
<h3>Organizations</h3>
</div>
<div class="container">
<div class="row">
    <% @organizations.each do |organization| %>
    <div class="col-md-3 col-xs-12 ">
        <%= link_to "#{organization.name}", organization_path(organization) %>
        <%= organization.about %>
        <%= organization.url %>
        <%= image_tag organization.logo.url(:thumb) %>
    </div>
    <% end %>
</div>
</div>
<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<div class="container row">
<div class="col-lg-offset-3 col-md-offset-3 col-lg-9 col-md-6 col-xs-12">
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', organizations_path %>
</div>
</div>

app/views/organizations/show.html.erb
<div class="container">
<div class="col-sm-offset-3 col-sm-6">
<%= render 'organizations/show' %>
<br>
<% if @signed_in %>
<%= link_to 'Edit', edit_organization_path(@organization) %> | 
<% end %>
<%= link_to 'Back', organizations_path %>
</div>
</div>