config/routes.rb
Rails.application.routes.draw do
  root 'animals#index'
  devise_for :admins
  resources :organizations
  resources :animals
  get "/about", to:"organizations#about", as:"about"
  get "/faq", to:"organizations#faq", as:"faq"
  get "/contact" => 'organizations#about'
  post "/contact", to:"organizations#contact"
  post 'animals/:id/purchase' => 'animals#purchase', as: :purchase
  get 'animals/:id/purchase_succeeded' => 'animals#purchase_succeeded', as: :purchase_succeded
  get 'animals/:id/purchase_failed' => 'animals#purchase_failed', as: :purchase_failed

end

app/views/layouts/_header.html.erb
<nav id="topnavbar" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="ml1"><%= image_tag("Logo2.png", width: '235') %></div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul id="topmenuitems" class="mr2 nav navbar-nav navbar-right">
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Find & Donate<span class="caret"></span></a>
          <ul id="dropdownmenu" class="dropdown-menu">
            <li><a href="#">Animal need</a></li>
            <li><a href="#">Animal rescue</a></li>
            <li><a href="#">Sanctuary request</a></li>
            <li role="separator" class="divider"></li>
            <li>
            <form class="navbar-form" role="search">
            <div class="form-group">
            <input id="dropdownsearch" type="text" class="form-control" placeholder="Search">
            <button id="submitsearch" type="submit" class="btn btn-default">
		Submit
	    </button>
	    <div>
            </form>
            </li>
          </ul>
        </li> -->
        <li><%= link_to "Home", root_path %></li>
	<li id="donateButton"><%= link_to "Donate", root_path(anchor: "donation_section") %></li>
	<li><%= link_to "How This Works", faq_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if admin_signed_in? %>
        <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		Welcome <%= current_admin.fullName %><span class="caret"></span>
            </a>
            <ul id="dropdownmenu" class="dropdown-menu">
            <li><%= link_to 'New Animal', new_animal_path %></li>
            <li><%= link_to 'Sign Out', destroy_admin_session_path, method: :delete %></li>
	    </ul>
	</li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Animalwishes</title>
  <meta name="description" content="Donate to Sanctuaries that have rescued farm & domestic Animals.100% of your support goes towards the Animals.">
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>